### PR TITLE
translate eth/EVM_Opcode159

### PR DESCRIPTION
**Pull request by JixiangSoong**
file name:EVM_Opcode159.md

related to issue: https://github.com/lbc-team/Pioneer/issues/159

### CODE REVIEW

**Review by xilibi2003 — APPROVED** [review]

**Comment by Nami-upchain** [comment]
@JixiangSoong 请回复一下在登链社区网站的账号或者个人主页链接，要给你发学分奖励

**Comment by Nami-upchain** [comment]
或者微信私信晓娜（upchainedu），谢谢

**Comment by JixiangSoong** [comment]
https://learnblockchain.cn/people/12540 @Nami-upchain 登链主页，谢谢🙏

**Comment by Nami-upchain** [comment]
已经发啦

**Pull request merged**
